name: E2E

on:
  push:
    branches: ["main", "master"]
  pull_request: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Run end-to-end tests
        working-directory: test/e2e
        env:
          REPO_ROOT: ${{ github.workspace }}
        run: go test -v ./...
