name: Tests

on:
  push:
    branches: ["main", "master"]
  pull_request: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Run adapter unit tests
        working-directory: services/envoy/adapter
        run: go test ./...

      - name: Run API unit tests
        working-directory: services/api
        run: go test ./...

      - name: Run end-to-end integration tests
        working-directory: tests/e2e
        run: go test ./...
